name: Tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install dependancies
        run: npm install

      - name: Build
        run: npm run build


  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install dependancies
        run: npm install

      - name: Build
        run: npm run test